package logic;

public enum GameEvent {
    SEARCHED_FAST_FOOD_STAND,
    TOOK_MEDKIT,
    BURGER_EATEN,
    TUTORIAL_PASSED,
    TOOK_MEDKIT_EAG,
    TOOK_BOOTS,
    EAT_FOOD,
    TOOK_KEY,
    IS_ENDLESS,
    FIRST_SHOP_VISIT,
    STARTED_RANDOM_ROOM,
    TOOK_SODA,
    SUBWAY_ZOMBIE_FOUGHT,
    KIOSK_ZOMBIE_DEFEATED
}

